
import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author irwan
 */
public class PilihGambarButton extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonPanel = new javax.swing.JPanel();
        BukuJava1BT = new javax.swing.JButton();
        KapalBT = new javax.swing.JButton();
        BukuJavaBT = new javax.swing.JButton();
        ExitBT = new javax.swing.JButton();
        ImagePanel = new javax.swing.JPanel();
        BukuJava1LB = new javax.swing.JLabel();
        KapalLB = new javax.swing.JLabel();
        BukuJavaLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BukuJava1BT.setText("Buku java 1");
        BukuJava1BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BukuJava1BTActionPerformed(evt);
            }
        });
        ButtonPanel.add(BukuJava1BT);

        KapalBT.setText("Kapal");
        KapalBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KapalBTActionPerformed(evt);
            }
        });
        ButtonPanel.add(KapalBT);

        BukuJavaBT.setText("Buku Java 2");
        BukuJavaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BukuJavaBTActionPerformed(evt);
            }
        });
        ButtonPanel.add(BukuJavaBT);

        ExitBT.setText("Exit");
        ExitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBTActionPerformed(evt);
            }
        });
        ButtonPanel.add(ExitBT);

        getContentPane().add(ButtonPanel, java.awt.BorderLayout.PAGE_START);

        ImagePanel.setLayout(new java.awt.CardLayout());

        BukuJava1LB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buku Java2.JPG"))); // NOI18N
        ImagePanel.add(BukuJava1LB, "0");

        KapalLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kapal bajak laut.jpg"))); // NOI18N
        ImagePanel.add(KapalLB, "1");

        BukuJavaLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java buku.jpg"))); // NOI18N
        ImagePanel.add(BukuJavaLB, "2");

        getContentPane().add(ImagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BukuJava1BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BukuJava1BTActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout)(ImagePanel.getLayout());
        c1.show(ImagePanel, "0");
    }//GEN-LAST:event_BukuJava1BTActionPerformed

    private void KapalBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KapalBTActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout)(ImagePanel.getLayout());
        c1.show(ImagePanel, "1");
    }//GEN-LAST:event_KapalBTActionPerformed

    private void BukuJavaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BukuJavaBTActionPerformed
        // TODO add your handling code here:
         CardLayout c1 = (CardLayout)(ImagePanel.getLayout());
        c1.show(ImagePanel, "2");
    }//GEN-LAST:event_BukuJavaBTActionPerformed

    private void ExitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBTActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PilihGambarButton fullFrame = new PilihGambarButton();
                
                GraphicsDevice device = 
                        GraphicsEnvironment.getLocalGraphicsEnvironment() .getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BukuJava1BT;
    private javax.swing.JLabel BukuJava1LB;
    private javax.swing.JButton BukuJavaBT;
    private javax.swing.JLabel BukuJavaLB;
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JButton ExitBT;
    private javax.swing.JPanel ImagePanel;
    private javax.swing.JButton KapalBT;
    private javax.swing.JLabel KapalLB;
    // End of variables declaration//GEN-END:variables
}
